server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  compression:
    enabled: true
    mime-types: text/html,text/xml,text/css,text/javascript,application/json,application/javascript,application/x-font-ttf
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto

spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        enable_lazy_load_no_trans: true
        jdbc:
          lob:
            non_contextual_creation: true
        criteria:
          literal_handling_mode: BIND
    show-sql: false
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    name: region
    url: @region.datasource.url@
    username: @region.datasource.username@
    password: @region.datasource.password@
    hikari:
      pool-name: MainDBPool
      auto-commit: false
      idle-timeout: 90000
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 50
      max-lifetime: 300000
      driver-class-name: org.postgresql.Driver
      schema: public
  servlet:
    multipart:
      max-file-size: 10MB
